spring:
   jpa:
      generate-ddl: true
      show-sql: true
      hibernate:
         ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      properties:
         hibernate:
            format_sql: true
   datasource:
      url: jdbc:mysql://localhost:3306/flowable-test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: songyz
      driver-class-name: com.mysql.jdbc.Driver
logging:
   pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{500} %caller{depth} %line - %m%n'
   level:
      root: info