server:
  port: 9090
  servlet:
    context-path: /
spring:
  application:
    name: elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
logging:
  level:
    root: INFO
    org.hibernate: INFO